# 1. Create a 3x3x3 array with random values.

In [4]:
import numpy as np

random_arr= np.random.randint(3,100,size=(3,3,3))

random_arr

array([[[64, 22, 96],
        [63, 91, 84],
        [34,  3,  8]],

       [[94,  9,  7],
        [56, 88, 55],
        [36, 21, 85]],

       [[37, 52, 12],
        [86, 52, 44],
        [ 7, 16, 66]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.

In [5]:
np.diag([1,2,3,4] , -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern.

In [7]:
import numpy as np

print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix.

In [8]:
import numpy as np

x = np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.51296302 0.41310567 0.75785291 0.92408261 0.48359105]
 [0.49612023 0.43377159 0.31901874 0.14404682 0.37813841]
 [0.40739813 0.62140737 0.31926635 0.99544289 0.77509293]
 [0.38379751 0.34171857 0.09650684 0.81619681 0.80583964]
 [0.02978755 0.2157967  0.77964973 0.60642562 0.00913451]]
After normalization:
[[0.5108225  0.40957896 0.75911187 0.92764912 0.48104279]
 [0.4937459  0.43053176 0.31418594 0.13678511 0.37412629]
 [0.40379219 0.62077224 0.31443699 1.         0.77659121]
 [0.37986395 0.33720089 0.0885852  0.81826568 0.80776474]
 [0.02093974 0.20953101 0.78121127 0.60558252 0.        ]]


# 5. How to find common values between two arrays?

In [9]:
import numpy as np

array1 = np.array([0, 1, 2, 4, 6])
print("Array 1: ",array1)
array2 = np.array([1, 3, 4])
print("Array 2: ",array2)
print("Common values between the arrays:")
print(np.intersect1d(array1, array2))
np.set_printoptions(threshold=np.inf)

Array 1:  [0 1 2 4 6]
Array 2:  [1 3 4]
Common values between the arrays:
[1 4]


# 6.How to get the dates of yesterday, today and tomorrow?

In [10]:
import numpy as np

yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-08-01
Today:  2020-08-02
Tomorrow:  2020-08-03


# 7. Consider two random array A and B, check if they are equal.

In [12]:
A = np.array([[1,2],[3,6]])
B = np.array([[1,2],[3,6]])
comparison = A == B
equal_arrays = comparison.all()
print(equal_arrays)

True


# 8.Create random vector of size 10 and replace the maximum value by 0.

In [13]:
from numpy import array

print("Random vector of size 10:")
v = np.random.randint(1,20, size = 10)
print(v)
v[v.argmax()] = 0
print("\nReplacing the maximum value by 0:")
print(v)

Random vector of size 10:
[ 2  8 10  5  6 13  7  6  9 13]

Replacing the maximum value by 0:
[ 2  8 10  5  6  0  7  6  9 13]


# 9. How to print all the values of an array?

In [14]:
x = np.arange(101)
np.set_printoptions(threshold=np.inf)
print(x)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


# 10.Subtract the mean of each row of a matrix.

In [15]:
import numpy as np

print("Original matrix:\n")
a = np.arange(12).reshape(3,4)
print(a)
print("\nSubtract the mean of each row of the matrix:\n")
b = a - a.mean(axis=1, keepdims = True)
print(b)

Original matrix:

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Subtract the mean of each row of the matrix:

[[-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [16]:
#Given Vector

a = np.random.randint(1,8,8)
print("Given vector:", a)
b = np.random.randint(a)
c = []
b.sort()
for i in b:
    if i not in c:
        c.append(i)

for j in c:
    a[j] += 1

print("Indexing vector:", b)
print("Result:",a)

Given vector: [2 2 1 2 1 2 7 7]
Indexing vector: [0 0 0 0 1 1 2 3]
Result: [3 3 2 3 1 2 7 7]


# 12.How to get the diagonal of a dot product?

In [17]:
X = [[1,2],[3,4]]
Y = [[1,2],[3,4]]
Z = np.diag(np.dot(X,Y))
Z

array([ 7, 22])

# 13.How to find the most frequent value in an array?

In [18]:
import numpy as np

x = np.random.randint(0, 10, 20)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[0 7 0 1 7 2 5 3 5 7 9 4 3 6 1 3 8 4 0 4]
Most frequent value in the above array:
0


# 14.How to get the n largest values of an array?

In [19]:
import numpy as np

x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print("Largest value of the array is",x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
Largest value of the array is [9]


# 15.How to create a record array from a regular array?

In [20]:
import numpy as np

a1=np.array(['Apple','Car','Bike','Sky'])
a2=np.array(['Red','Grey','Orange','Blue'])
result= np.core.records.fromarrays([a1, a2])
print(result[0])
print(result[1])
print(result[2])

('Apple', 'Red')
('Car', 'Grey')
('Bike', 'Orange')
